### ISSUE TITLE
BadRecord, block error in NOVLNS

### ISSUE THREAD

**Issue by jxs1** [ArchainTeam/archain#4]
Bad record, block line 69, ar_fork_recovery

**Comment by samcamwilliams** [comment]
Got any more information about the context in which this arises, @jxs1?

Thanks!
sam

**Comment by jxs1** [comment]
All the info I have. Written on post it note from a while ago after I found it. All I recall is a repeated error from latest BATN.3 (?) running on core servers. 

This is the reason I started issue tracker. Small bugs like this might become forgotten or never chased.

**Comment by archain-team** [comment]
Ok, let's leave this open for now and add information when we encounter it again.

Sam

**Comment by wrj-arc** [comment]
Fixed in ATN1.
